
public class ExceptionEx {

	public static void main(String[] args) {
	
		int n1 = 20;
		int n2 = 10; 
		float result;
		
		try {
			result = n1/n2;
			
			System.out.println("Division is : "+result);
		}
		catch(ArithmeticException e) {
			
			System.out.println(e);
		}
		System.out.println("Thank You !!");
		
	}

}
